### ISSUE TITLE
Need Linux binary to v1.4.3 commit on a release

### ISSUE THREAD

**Issue by ulc-brian** [imagemin/jpegoptim-bin#14]
Can you please create a new release which includes these changes that are already on master. I depend on a package, imagemin-jpegoptim, that requires package and it is set to use ^3.0.0, but with that version your binary isn't at 1.4.3, its at 1.4.1 and I need it to be 1.4.3. If you were to create another release it would solve my problems, thanks!

**Comment by sindresorhus** [comment]
New version is out now.
