### ISSUE TITLE
I would like to know how your jpegoptim.exe is compiled, I would like to learn

### ISSUE THREAD

**Issue by AlanSean** [imagemin/jpegoptim-bin#23]
I would like to know how your jpegoptim.exe is compiled, I would like to learn。
I will only compile binaries that support Linux under Linux。
Could you please teach me！！！

**Comment by 1000ch** [comment]
Please follow [this instruction](https://github.com/tjko/jpegoptim).

**Comment by XhmikosR** [comment]
This is the repo with the scripts that I use to build the binaries we use in this repo: https://github.com/XhmikosR/jpegoptim-windows
