### ISSUE TITLE
Cannot build on CentOS 7

### ISSUE THREAD

**Issue by sup3rman** [imagemin/jpegoptim-bin#3]
Hi,

I have tried installing jpegoptim-bin on three different Digital Ocean droplets running CentOS 7 (x64). I get the same error on all three.

```
> jpegoptim-bin@2.0.1 postinstall /home/tcbeer/node_modules/jpegoptim-bin
> node lib/install.js

  ⚠ The `jpegoptim` binary doesn't seem to work correctly
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --prefix="/home/tcbeer/node_modules/jpegoptim-bin/vendor" --bindir="/home/tcbeer/node_modules/jpegoptim-bin/vendor" && make install && mv /home/tcbeer/node_modules/jpegoptim-bin/vendor/bin/jpegoptim /home/tcbeer/node_modules/jpegoptim-bin/vendor/jpegoptim
Command failed: 
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by crobays** [comment]
Hi sup3rman,

I also ran into this issue and found the solution. When installing this package it validates the jpegoptim binary by running `jpegoptim --version` If that command returns an error it wants to make the binary by itself, but probably because there are no make tools installed it can't.

Test by yourself by running

    node_modules/jpegoptim-bin/vendor/jpegoptim --version

Running that command gave me the following error:
    
    node_modules/jpegoptim-bin/vendor/jpegoptim: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

The solution is to make that `--version` command to work by installing libjpeg via yum (or apt-get in my case), see https://github.com/zakird/wkhtmltopdf_binary_gem/issues/19

Now it successfully executes the `--version` command

I hope this works for you.

**Comment by sup3rman** [comment]
Hmmm, I get the same Error as you do, when calling the command you supplied. However, I already have libjpeg installed (actually libjpeg-turbo), so unfortunately your solution does not help.

**Comment by shinnn** [comment]
We just updated the [installation instructions](https://github.com/imagemin/jpegoptim-bin#install).

> Make sure you have the correct version of libjpeg. See [jpegoptim's README](https://github.com/tjko/jpegoptim#readme) for more information.

`apt-get install libjpeg62 libjpeg62-dev` would solve the problem.

**Comment by seltix5** [comment]
Hello,
I'm having the same problem. My server provider is using CentOS6 and the libjpeg.so.62 is installed but since it is not the same version it does not work.
Is it possible to make a version to work with libjpeg.so.62 ?

**Comment by aderrr** [comment]
Hello all,
wkhtmltopdf: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
libjpeg-turbo  1.2.90-5.14.amzn1

**Comment by aderrr** [comment]
install libjpeg-turbo-official-1.5.2.x86_64 
wkhtmltopdf: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory

**Comment by aderrr** [comment]
in /usr/lib64 & /opt/libjpeg-turbo/lib64  file in directory!
