### ISSUE TITLE
Binaries “doesn’t seem to work correctly”

### ISSUE THREAD

**Issue by timseverien** [imagemin/jpegoptim-bin#7]
It appears something is wrong with the precompiled binaries, and they can’t be compiled from source either.

OS X El Capitan (10.11.2)
node v5.5.0
npm 3.3.12

GNU Make 3.81, built for i386-apple-darwin11.3.0

```
⚠ The `/Users/Tim/***/node_modules/jpegoptim-bin/vendor/jpegoptim` binary doesn't seem to work correctly
⚠ jpegoptim pre-build test failed
ℹ compiling from source
✖ Error: ./configure --prefix="/Users/Tim/***/node_modules/jpegoptim-bin/vendor" --bindir="/Users/Tim/***/node_modules/jpegoptim-bin/vendor" && make install
Command failed: /bin/sh -c ./configure --prefix="/Users/Tim/***/node_modules/jpegoptim-bin/vendor" --bindir="/Users/Tim/***/node_modules/jpegoptim-bin/vendor"
```

Let me know if you need additional information.

**Comment by shinnn** [comment]
Does your environment satisfy the [jpegoptim requirements](https://github.com/tjko/jpegoptim#readme)?

> REQUIREMENTS
> 	Independent JPEG Group's jpeg library (libjpeg) version 6b or later
> 	(jpegsrc.v6b.tar.gz)

**Comment by timseverien** [comment]
Apparently not. It looked like the system administrator installed a libjpeg fork through ports, which didn’t work. After installing libjpeg through brew and reinstalling the package, everything worked perfectly. So sorry to bother you with my stupidity.

Thank you so much for the fast reply. We’re 5 minutes away from a deadline D:

**Comment by shinnn** [comment]
@timseverien No problem!
